cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_AAC\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_AAC\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_AC3\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_AC3\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_APE\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_APE\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_MP3\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_MP3\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_MPC\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_MPC\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_VORBI\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_VORBI\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_WAVPA\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\AD_WAVPA\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\FFMPEGAC\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\FFMPEGAC\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DEMUXERS\MP4FF\
call E:\DEV\MSVC_Projects\MPXPlay\source\DEMUXERS\MP4FF\W.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\AU_CARDS\
call E:\DEV\MSVC_Projects\MPXPlay\source\AU_CARDS\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\AU_MIXER\
call E:\DEV\MSVC_Projects\MPXPlay\source\AU_MIXER\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\CONTROL\
call E:\DEV\MSVC_Projects\MPXPlay\source\CONTROL\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\
call E:\DEV\MSVC_Projects\MPXPlay\source\DECODERS\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DEMUXERS\
call E:\DEV\MSVC_Projects\MPXPlay\source\DEMUXERS\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DEPARSER\
call E:\DEV\MSVC_Projects\MPXPlay\source\DEPARSER\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DISKDRIV\
call E:\DEV\MSVC_Projects\MPXPlay\source\DISKDRIV\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\DISPLAY\
call E:\DEV\MSVC_Projects\MPXPlay\source\DISPLAY\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\NEWFUNC\
call E:\DEV\MSVC_Projects\MPXPlay\source\NEWFUNC\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\PLAYLIST\
call E:\DEV\MSVC_Projects\MPXPlay\source\PLAYLIST\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\VIDEOOUT\
call E:\DEV\MSVC_Projects\MPXPlay\source\VIDEOOUT\WD.BAT
cd E:\DEV\MSVC_Projects\MPXPlay\source\